config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :index] do 
    resources :dashboard, only: [:index]
    resources :trips
    resources :stadiums
    resources :games
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :password, presence: true
  validates :password, confirmation: {case_sensitive: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

  def require_same_user
    if @current_user != @host
      flash[:alert] = "You can only access your own dashboard"
      redirect_to user_dashboard_index_path(@current_user)
    end
  end

  helper_method :current_user, :logged_in?, :require_user, :require_same_user
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome to your dashboard, #{user.name}!"
      redirect_to user_dashboard_index_path(user)
    else
      flash[:error] = 'Credentials do not match'
      render :login_form
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root
  end

  private
  def user_params
    params.permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = user_params
    user[:email] = user[:email].downcase
    new_user = User.create!(user)
    if new_user.save
      session[:user_id] = new_user.id
      flash[:success] = "Welcome to your dashboard, #{new_user.name}!"
      redirect_to user_dashboard_index_path(new_user)
    else
      render :new
      flash[:error] = new_user.errors.full_messages.to_sentence
    end
  end

  private
  def user_params
    params.permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome to your dashboard, <%= @user.name %>!</h1>

<h2>View Your Trips</h2>

<h2>View Your Visited Ballparks</h2>

<h2>View Your Attended Games</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ballparks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= button_to "Logout", logout_path, method: :get %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up For A Free Account</h1>

<h3>Please enter your full name, email address, and password to create an account.</h3>

<%= form_with url: users_path, method: :post, local: true do |f| %>
  <%= f.label :name, 'Name:' %>
  <%= f.text_field :name %><br><br>
  <%= f.label :email, 'Email:' %>
  <%= f.text_field :email %><br><br>
  <%= f.label :password, 'Password:' %>
  <%= f.password_field :password %><br><br>
  <%= f.label :password_confirmation, 'Password Confirmation:' %>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.submit 'Register' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome To Stadium Tracker!</h1>
<h2>A place to store and track your trips around the 30 Major League Ballparks!</h2>

<h3>Already a User? <%= link_to 'Login', login_path %></h3>
<h3>If Not, <%= link_to 'Register Here', new_user_path %></h3>